
name: Web CD

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'    
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: Infra/package-lock.json

    - name: Install dependencies
      run: npm install 
      
    - name: Build web app
      working-directory: ./packages/web
      run: yarn build

    - name: Install dependencies
      working-directory: Infra
      run: npm ci

    - name: cdk deploy infra
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        working_dir: 'Infra'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'



