
name: Web CD

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'    
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    # Instalar dependencias y construir la aplicación web
    - name: Install web app dependencies
      working-directory: packages/web
      run: npm install

    - name: Build web app
      working-directory: packages/web
      run: npm run build

    # Instalar dependencias y desplegar la infraestructura con AWS CDK
    - name: Install Infra dependencies
      working-directory: Infra
      run: npm install

    - name: Deploy infrastructure with CDK
      working-directory: Infra
      run: npx cdk deploy --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'